# lists of SRA numbers (metaG)
human_SRA: "/group/ctbrowngrp2/amhorst/2025-pig-v-human/config/human_sra.txt"
pig_100: "/group/ctbrowngrp2/amhorst/2025-pig-v-human/config/pig_100.txt"
pig_no_atlas: "/group/ctbrowngrp2/amhorst/2025-pig-v-human/config/pig_sra_noatlas.txt"
all_pig_atlas: "/group/ctbrowngrp2/amhorst/2025-pig-v-human/config/pig_sra.txt"
pig_test: "/group/ctbrowngrp2/amhorst/2025-pig-v-human/config/pig-test.txt"

# organism of interest
pang_org: "Lactobacillus amylovorus"


# outfolder name
pang_folder: "l_amylovorus"